version: "3"

services:
    app:
        container_name: ${APP_CONTAINER_NAME}
        image: ${APP_IMAGE}
        build:
            context: ./app
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        restart: always
        volumes:
            - ./app/src:/app
        ports:
            - ${APP_PORT}:9000
        networks:
            - default
        depends_on:
            - postgres
            - redis
    postgres:
        container_name: ${POSTGRES_CONTAINER_NAME}
        image: ${POSTGRES_IMAGE}
        build:
            context: ./postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/data/postgres
        restart: always
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - default
    redis:
        container_name: ${REDIS_CONTAINER_NAME}
        image: ${REDIS_IMAGE}
        build:
            context: ./redis
            args:
                - REDIS_PASSWORD=${REDIS_PASSWORD}
        restart: always
        volumes:
            - ./data/redis:/data
        ports:
            - ${REDIS_PORT}:6739
        networks:
            - default
networks:
    default:
        driver: bridge
